meta_product_name: "Compet' en Vill'"
meta_title: "Compet' en Vill'- Ornganiser des match au city-stade"
meta_description: "Inscrivez-vous pour rester informé(e), bientôt dans toutes vos villes et villages"
meta_image: "stade.jpg" # should exist in `app/assets/images/`
