meta_product_name: "Compet' en Vill'"
meta_title: "Compet' en Vill' - Organiser des matchs au city-stade ! "
meta_description: "Vous facilite l'organisation de matchs au city-stade !"
meta_image: "stade.jpg" # should exist in `app/assets/images/`
