meta_product_name: "Compet' en Vill'"
meta_title: "Compet' en Vill'- Ornganise des matchs au city-stade"
meta_description: "Inscrivez-vous pour rester informé(e). L'application sort bientôt dans toutes les villes et les villages de France"
meta_image: "stade.jpg" # should exist in `app/assets/images/`
