meta_product_name: "Compet' en Vill'"
meta_title: "Compet' en Vill' vous facilite l'organisation de match au city-stade ! "
meta_description: "Inscrivez-vous pour rester informé(e) !"
meta_image: "stade.jpg" # should exist in `app/assets/images/`
